In [26]:
import numpy as np
import tensorflow as tf
from PIL import Image
import matplotlib.pyplot as plt
from misc_helpers import *

In [6]:
tf.zeros((2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [12]:
a = tf.experimental.numpy.random.randint(0, 10, (5, 10))
print(a)
b = tf.concat([a[:, :1], a[:, :-1]], axis = 1)
b


ndarray<tf.Tensor(
[[9 8 1 6 9 0 9 7 7 0]
 [8 6 6 5 8 1 6 2 6 7]
 [4 4 6 0 1 0 4 8 6 2]
 [1 7 4 6 5 2 9 8 3 9]
 [2 3 7 7 7 6 6 4 3 9]], shape=(5, 10), dtype=int32)>


<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[9, 9, 8, 1, 6, 9, 0, 9, 7, 7],
       [8, 8, 6, 6, 5, 8, 1, 6, 2, 6],
       [4, 4, 4, 6, 0, 1, 0, 4, 8, 6],
       [1, 1, 7, 4, 6, 5, 2, 9, 8, 3],
       [2, 2, 3, 7, 7, 7, 6, 6, 4, 3]])>

In [2]:
img = Image.open('test_img.jpg')

In [4]:
w, h = img.size
w, h

(1950, 1300)

In [12]:
def change_ext(file, new_ext):
    ri = file.rindex('.')
    return file[:ri] + '.' + new_ext

outfile = 'resized_image.jpg'
outfile = change_ext(outfile, 'png')

'resized_image.png'

In [8]:


resized = img.resize((w//4, h//4), Image.ANTIALIAS)
resized.save(outfile)

In [12]:
image_folder = 'data/rubiks/cropped/images'

In [25]:
images = os.listdir(image_folder)
np.random.shuffle(images)
images

['rubiks_1_07.jpg',
 'rubiks_4_31.jpg',
 'rubiks_3_09.jpg',
 'rubiks_2_04.jpg',
 'rubiks_3_04.jpg',
 'rubiks_4_29.jpg',
 'rubiks_5_03.jpg',
 'rubiks_2_09.jpg',
 'rubiks_2_28.jpg',
 'rubiks_2_29.jpg',
 'rubiks_1_26.jpg',
 'rubiks_3_29.jpg',
 'rubiks_1_16.jpg',
 'rubiks_4_16.jpg',
 'rubiks_2_25.jpg',
 'rubiks_4_09.jpg',
 'rubiks_1_29.jpg',
 'rubiks_2_16.jpg',
 'rubiks_3_19.jpg',
 'rubiks_2_17.jpg',
 'rubiks_4_24.jpg',
 'rubiks_2_26.jpg',
 'rubiks_1_08.jpg',
 'rubiks_1_04.jpg',
 'rubiks_1_11.jpg',
 'rubiks_1_10.jpg',
 'rubiks_4_22.jpg',
 'rubiks_2_27.jpg',
 'rubiks_3_27.jpg',
 'rubiks_1_23.jpg',
 'rubiks_2_19.jpg',
 'rubiks_1_25.jpg',
 'rubiks_4_12.jpg',
 'rubiks_3_07.jpg',
 'rubiks_1_21.jpg',
 'rubiks_2_05.jpg',
 'rubiks_1_19.jpg',
 'rubiks_1_14.jpg',
 'rubiks_2_11.jpg',
 'rubiks_2_13.jpg',
 'rubiks_2_03.jpg',
 'rubiks_1_28.jpg',
 'rubiks_2_00.jpg',
 'rubiks_3_30.jpg',
 'rubiks_3_06.jpg',
 'rubiks_1_06.jpg',
 'rubiks_3_02.jpg',
 'rubiks_3_31.jpg',
 'rubiks_3_00.jpg',
 'rubiks_4_18.jpg',


In [ ]:
plot_images